version: '3.8'

services:
  db:
    image: postgres:15-alpine # İnternetten hazır PostgreSQL indir
    container_name: security_db
    environment:
      POSTGRES_USER: postgres       # Kendi DB kullanıcı adın
      POSTGRES_PASSWORD: 1234       # Kendi DB şifren
      POSTGRES_DB: security_db # Kendi DB adın
    #5433 docker, 5432 windows
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: security_rabbitmq
    ports:
      - "5672:5672"   # Spring Boot'un arka planda mesajlaşmak için kullanacağı kapı
      - "15672:15672" # Bizim tarayıcıdan yönetim paneline gireceğimiz kapı

  redis:
    image: redis:7-alpine
    container_name: security_redis
    ports:
      - "6379:6379" # Redis'in dış dünyayla iletişim kurduğu standart kapı

  prometheus:
    image: prom/prometheus:latest
    container_name: security_prometheus
    ports:
      - "9090:9090"
    volumes:
      # Az önce yazdığımız haritayı Prometheus'un içine kopyalıyoruz
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: security_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  app:
    build: . # Bu klasördeki Dockerfile'ı bul ve inşa et
    container_name: security-app
    # ports:
    #    - "8080:8080"
    depends_on:
      - db # Önce veritabanı (db) ayağa kalksın, sonra uygulama çalışsın
      - rabbitmq
    environment:
      # ÇOK KRİTİK: Artık veritabanı "localhost" değil, üstteki servisin adı olan "db" oldu!
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/security_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - RABBIT_HOST=security_rabbitmq