spring.application.name=security

spring.datasource.url=jdbc:postgresql://localhost:5433/security_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.rabbitmq.host=${RABBIT_HOST:127.0.0.1}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.data.redis.host=redis
spring.data.redis.port=6379

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true